name: Deploy ASP.NET Core to Somee

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./EVCare_BackEnd/API/API.csproj

    - name: Build project
      run: dotnet build ./EVCare_BackEnd/API/API.csproj --configuration Release --no-restore

    - name: Publish project
      run: dotnet publish ./EVCare_BackEnd/API/API.csproj -c Release -o ./publish

    - name: FTP Deploy to Somee
      uses: SamKirkland/FTP-Deploy-Action@v4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./publish
        server-dir: /
